### ISSUE TITLE
Can not download the  synthesis model for face mask

### ISSUE THREAD

**Issue by shuishiwojiade** [MontaEllis/SD-GAN#2]
Thanks for your work. But I can not download the  synthesis model for face mask or glass.
![can not down](https://github.com/MontaEllis/SD-GAN/assets/23050341/dcfaf95f-893d-4d6a-8274-f4e64f661e1d)

**Comment by MontaEllis** [comment]
Thank you for your interest in this paper. We have updated the permissions accordingly.
